# Generated by Django 5.0.6 on 2024-05-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=6)),
            ],
        ),
    ]
