# Generated by Django 5.0.4 on 2024-06-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_sex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_employeed',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='employee',
            name='occupation_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_information',
            field=models.CharField(default='Unknown', max_length=1021),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identity_card',
            field=models.CharField(default='Unknown', max_length=18),
        ),
    ]
