# Generated by Django 5.0.6 on 2024-05-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0002_transfer_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.AlterField(
            model_name='transfer_record',
            name='transfer_date',
            field=models.DateTimeField(),
        ),
    ]
