# Generated by Django 5.0.6 on 2024-06-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0002_employee_employee_sex_employee_is_employeed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_user',
            name='annual_income',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='online_user',
            name='property_valuation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='online_user',
            name='service_year',
            field=models.IntegerField(null=True),
        ),
    ]
