# Generated by Django 5.0.6 on 2024-05-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0003_delete_creditcard_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transfer_record',
            new_name='Transaction',
        ),
    ]
