# Generated by Django 5.0.4 on 2024-05-31 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0005_employee_online_user_creditcardexaminer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='online_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='creditcard.online_user'),
        ),
    ]
