# Generated by Django 5.0.6 on 2024-06-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0007_alter_creditcardapplication_creditcardexaminer'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardapplication',
            name='have_open',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SystemManager',
        ),
    ]
